export default data = {
  year2080: [
    {
      id: 1,
      titleEnglish: "Book Distribution Program",
      titleNepali: "पुस्तक हस्तान्तरण कार्यक्रम  ",
      descEnglish:
        "नेपाल महिला संघका संस्थापक अध्यक्ष मंगला देवी सिंहको फोटो फ्रेम र `नारी संघर्ष का पाईलाहरू` पुस्तक नेपाल महिला संघका सम्पुर्ण जिल्ला अफिसलाई हस्तान्तरण कार्यक्रम आयोजक: मंगला देवी सिंह फाउण्डेशन  चाक्सीबारी, काठमाण्डौ।",
      descNepali: `Photo frame of Mangala Devi Singh, founder president of Nepal Women's Association and handing over the book "Steps of Women's Struggle" to the entire district offices of Nepal Women's Association.
        Organizer: Mangala Devi Singh Foundation
        Chaxibari, Kathmandu.`,
      date: "24th February, 2024",
      images: ["0101.jpg", "0102.jpg", "0103.jpg", "0104.jpg"],
    },

    {
      id: 2,
      titleEnglish: ` three months basic sewing training`,
      titleNepali: `तीन  महिने बेसिक सिलाई तालिम`,
      descEnglish: `Inauguration program of three months basic sewing training with technical support of Mangala Devi Singh Foundation and the help of Industry and Commerce Office. #BecomeEntrepreneur #BecomeFinanciallySelfDependent Place: Sohrakhutte, Kamanpa 16th Ward.`,
      descNepali: `मंगला देवी सिंह फाउण्डेशनको प्रविधिक सहयोग र उधोग तथा बाणिज्य कार्यालयको सहयोगमा तीन  महिने बेसिक सिलाई तालिम को उद्घघाटन कार्यक्रम। 
#उद्धमीबनौ #आर्थिकरूपमाआत्मनिर्भरबनौ 
स्थान: सोह्रखुट्टे , कामनपा १६ वार्ड।`,
      date: `March 22 2024 `,
      images: ["0201.jpg", "0202.jpg", "0203.jpg"],
    },
    {
      id: 3,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
    {
      id: 2,
      titleEnglish: ``,
      titleNepali: ``,
      descEnglish: ``,
      descNepali: ``,
      date: ``,
      images: [],
    },
  ],
  year2081: [],
};
